name: 'Raspberry Pi VM Runner'
description: 'Action to execute commands within a Raspberry Pi VM running on QEMU'
author: 'Brett Jia'

inputs:
  commands:
    description: 'Commands to run on the Pi, executed with /bin/bash'
    required: true
    default: 'uname -a'
  user:
    description: 'User to run commands on the Pi, either pi or root'
    required: true
    default: 'pi'
  prerun_copy_from:
    description: 'Path on the host to copy into the VM, before commands are executed'
    required: false
    default: ''
  prerun_copy_to:
    description: 'Path on the VM to copy files to, before commands are executed'
    required: false
    default: '/home/pi'
  postrun_copy_from:
    description: 'Path on the VM to copy to the host, after commands are executed'
    required: false
    default: ''
  postrun_copy_to:
    description: 'Path on the host to copy files to, after commands are executed'
    required: false
    default: '.'
  debug:
    description: 'Print debugging output from VM initialization and teardown'
    required: false
    default: 'no'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # Install dependencies
        sudo apt-get update -qq > /dev/null
        sudo apt-get install -y -qq qemu-system > /dev/null

        case "${{ inputs.debug }}" in
        yes|true)
          qemu-system-aarch64 -version
        ;;
        no|false)
        ;;
        esac

    - name: Download raspberry pi image
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Download raspberry pi image
        wget -O raspi.img.xz -q https://github.com/bjia56/qemu-raspi-images/releases/download/2023.02.22%2Barm64.lite.1/raspi.img.xz
        wget -O kernel.img -q https://github.com/bjia56/qemu-raspi-images/releases/download/2023.02.22%2Barm64.lite.1/kernel8.img
        wget -O rpi3bp.dtb -q https://github.com/bjia56/qemu-raspi-images/releases/download/2023.02.22%2Barm64.lite.1/bcm2710-rpi-3-b-plus.dtb
        case "${{ inputs.debug }}" in
        yes|true)
          xz -d -v raspi.img.xz
        ;;
        no|false)
          xz -d -v raspi.img.xz > /dev/null 2>&1
        ;;
        esac

    - name: Boot pi
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Boot pi
        case "${{ inputs.debug }}" in
        yes|true)
          sudo ./run_vm.sh &
          ./wait_for_ssh.sh 172.18.0.2 22 ${{ inputs.user }}
        ;;
        no|false)
          sudo ./run_vm.sh > /dev/null 2>&1 &
          ./wait_for_ssh.sh 172.18.0.2 22 ${{ inputs.user }} > /dev/null
        ;;
        esac
        
    - name: Add Raspberry Pi SSH config
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo -e "Host raspberrypi\n  HostName 172.18.0.2\n  User ${{ inputs.user }}" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

        mkdir -p ~/.local/bin
        cat > ~/.local/bin/raspberrypi << EOL
        #!/usr/bin/env sh
        ssh raspberrypi sh<\$1
        EOL
        chmod +x ~/.local/bin/raspberrypi
    
    - name: Copy files into pi
      shell: bash
      if: ${{ inputs.prerun_copy_from != '' }}
      run: |
        # Copy files into pi
        scp -r ${{ inputs.prerun_copy_from }} ${{ inputs.user }}@raspberrypi:${{ inputs.prerun_copy_to }}

    - name: Run commands
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Run commands
        cat <<- "RPIRUNNERSCRIPT" | ssh ${{ inputs.user }}@raspberrypi /bin/bash
        ${{ inputs.commands }}
        RPIRUNNERSCRIPT

    - name: Copy files from pi
      shell: bash
      if: ${{ inputs.postrun_copy_from != '' }}
      run: |
        # Copy files from pi
        scp -r ${{ inputs.user }}@raspberrypi:${{ inputs.postrun_copy_from }} ${{ inputs.postrun_copy_to }}

    - name: Stop pi
      shell: bash
      if: false
      working-directory: ${{ github.action_path }}
      run: |
        # Stop pi
        case "${{ inputs.debug }}" in
        yes|true)
          sudo ./kill_vm.sh
        ;;
        no|false)
          sudo ./kill_vm.sh > /dev/null 2>&1
        ;;
        esac
