name: 'Raspberry Pi VM Runner'
description: 'Action to execute commands within a Raspberry Pi VM running on QEMU'
author: 'Brett Jia'

inputs:
  commands:
    description: 'Commands to run on the Pi, executed with /bin/bash'
    required: true
    default: 'uname -a'
  user:
    description: 'User to run commands on the Pi, either pi or root'
    required: true
    default: 'pi'
  prerun_copy_from:
    description: 'Path on the host to copy into the VM, before commands are executed'
    required: false
    default: ''
  prerun_copy_to:
    description: 'Path on the VM to copy files to, before commands are executed'
    required: false
    default: '/home/pi'
  postrun_copy_from:
    description: 'Path on the VM to copy to the host, after commands are executed'
    required: false
    default: ''
  postrun_copy_to:
    description: 'Path on the host to copy files to, after commands are executed'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -qq >/dev/null
        sudo apt-get install -y -qq qemu-system >/dev/null
        qemu-system-aarch64 -version

    - name: Download raspberry pi image
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        wget -O raspi.img.xz -q https://github.com/bjia56/qemu-raspi-images/releases/download/2023.02.22%2Barm64.lite.0/raspi.img.xz
        wget -O kernel.img -q https://github.com/bjia56/qemu-raspi-images/releases/download/2023.02.22%2Barm64.lite.0/kernel8.img
        wget -O rpi3bp.dtb -q https://github.com/bjia56/qemu-raspi-images/releases/download/2023.02.22%2Barm64.lite.0/bcm2710-rpi-3-b-plus.dtb
        xz -d -v raspi.img.xz

    - name: Boot pi
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        sudo ./run_vm.sh &

        # Wait until ssh is up
        ./wait_for_ssh.sh 172.18.0.2 22 ${{ inputs.user }}

    - name: Copy files into pi
      shell: bash
      if: ${{ inputs.prerun_copy_from != '' }}
      run: |
        scp -r ${{ inputs.prerun_copy_from }} ${{ inputs.user }}@172.18.0.2:${{ inputs.prerun_copy_to }}

    - name: Run commands
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        cat <<- "RPIRUNNERSCRIPT" | ssh ${{ inputs.user }}@172.18.0.2 /bin/bash
        ${{ inputs.commands }}
        RPIRUNNERSCRIPT

    - name: Copy files from pi
      shell: bash
      if: ${{ inputs.postrun_copy_from != '' }}
      run: |
        scp -r ${{ inputs.user }}@172.18.0.2:${{ inputs.postrun_copy_from }} ${{ inputs.postrun_copy_to }}

    - name: Stop pi
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ssh root@172.18.0.2 halt || true
        sudo ./kill_vm.sh