name: Test copy to and from pi
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        cat 'hello world' > /tmp/hello.txt
    - uses: ./
      with:
        commands: |
          test `cat hello.txt` = 'hello world'
        prerun_copy_from: /tmp/hello.txt
        postrun_copy_from: /home/pi/hello.txt
    - run: |
        test `cat /tmp/hello.txt` = `cat hello.txt`