name: Test action
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  test_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        commands: |
          uname -m
          test `uname -m` = 'aarch64'

  test_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        commands: |
          docker run hello-world

  test_file_copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo 'helloworld' > /tmp/hello.txt
    - uses: ./
      with:
        commands: |
          test `cat hello.txt` = 'helloworld'
        prerun_copy_from: /tmp/hello.txt
        postrun_copy_from: /home/pi/hello.txt
    - run: |
        test `cat /tmp/hello.txt` = `cat hello.txt`