name: Test action
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  test_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        commands: |
          uname -m
          test `uname -m` = 'aarch64'

  test_simple_debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        debug: true
        commands: |
          uname -m
          test `uname -m` = 'aarch64'

  test_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        commands: |
          docker run hello-world

  test_file_copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo 'helloworld' > /tmp/hello.txt
    - uses: ./
      with:
        commands: |
          test `cat hello.txt` = 'helloworld'
        prerun_copy_from: /tmp/hello.txt
        postrun_copy_from: /home/pi/hello.txt
    - run: |
        test `cat /tmp/hello.txt` = `cat hello.txt`

  test_user_root:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        commands: |
          whoami
          test `whoami` = 'root'
        user: root

  test_user_pi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        commands: |
          whoami
          test `whoami` = 'pi'
        user: pi

  all_tests_passed:
    needs:
    - test_simple
    - test_simple_debug
    - test_docker
    - test_file_copy
    - test_user_root
    - test_user_pi
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "All tests passed!"